- hosts: localhost
  name: Install Weave Network using Kubectl from remote machine
  become: true
  become_user: ubuntu
  gather_facts: false

  vars:
    ansible_dir: "/home/ubuntu/kubernetes_the_hard_way/ansible"

  tasks:
    - name: Install Weave Network
      shell: |
        kubectl apply -f {{ ansible_dir }}/weave-daemonset-k8s.yaml
    
    - name: Pause for 1 minute to build Weave Net containers
      pause:
        minutes: 1

    - name: Get pods in kube-system namespace
      shell: kubectl get pods -n kube-system
      register: pods

    - name: Show kubectl get pods -n kube-system results and look out for Weave Net pods
      debug:
        msg:
        - "{{ pods.stdout_lines }}"
    
    - name: Check if the worker nodes are now ready
      shell: kubectl get nodes
      register: nodes
      no_log: True

    - name: Print the results of kubectl get nodes command
      debug:
        msg: "{{ nodes.stdout_lines }}"
